// PRJ.ARTE - DADOS

const introd = {
	titulo:"O Expressionismo Abstrato",
	subtitulo: "Algumas obras de seis grandes pintores",
	textoIntrod:[
		"O Expressionismo Abstrato foi um movimento artístico com origem nos Estados Unidos, cujo auge foi atingido nas décadas posteriores à Segunda Guerra Mundial. Foi o primeiro movimento especificamente americano a atingir influência mundial, colocando Nova Iorque no centro do mundo artístico (posição previamente exercida por Paris, na França). É por esse motivo que, na História da Arte, o Expressionismo Abstrato foi inicialmente designado por <i>Escola de Nova Iorque</i>.",
		"O movimento ganhou a designação de <i>Expressionismo Abstrato</i> por combinar a intensidade emocional do expressionismo alemão com a estética antifigurativa das Escolas abstratas da Europa, como o Futurismo, o Bauhaus e o Cubismo Sintético. O termo <i>Expressionismo Abstrato</i> foi usado pela primeira vez em 1952 pelo crítico e colecionador Harold Rosenberg para designar este movimento americano. São vários os pintores referidos como cultores do Expressionismo Abstrato, entre os quais se destacam os nomes de Arshile Gorky, Jackson Pollock, Philip Guston, Willem de Kooning, Mark Rothko, Adolph Gottliebe, Franz Kline, Robert Motherwell e Clyfford Still.",
		"A geração de Kooning e Pollock parecia ter sido, entre os expressionistas abstratos, composta por figuras em torno das quais a maioria dos críticos e dos artistas mais jovens se orientava. Incorporaram o emprego de uma paleta agressiva, conjugando os traços geométricos e aleatórios da <i>pintura automática</i>, um empaste pesado e grosseiro de pigmentos sobrepostos. O modo de pintar americano rompeu com a pintura de cavalete e elegeu como suporte a parede ou o chão, o que permitia que o artista tivesse uma nova capacidade para trabalhar dos quatro lados, passando a estar literalmente <i>na</i>, ou <i>dentro da</i> pintura. Utilizavam novos pigmentos, como o pesado empaste feito de areia, vidro moído, cinza vulcânica e a técnica do <i>dripping</i>.",
		"O Expressionismo Abstrato reúne um grande conjunto de manifestações, sendo possível identificar duas tendências principais. Uma, que se integra na corrente da <i>Action Painting</i>, inclui as obras de pintores como Jackson Pollock, Willem deKooning ou Franz Kline. Nas suas obras, bastante gestualistas, a tinta era lançada diretamente na tela, através de gestos instintivos, onde o acaso e o aleatório determinavam a evolução da pintura. A outra tendência, a <i>Color Field</i>, mais meditativa ou <i>mística</i>, integra os pintores Rothko e Gottlieb. Estes artistas exploraram preferencialmente as qualidades tácteis e os efeitos sensitivos da cor e produziram quadros abstratos utilizando poucos elementos, representados com limites indefinidos e relações cromáticas de grande subtileza."
	]
};

const pintores = [
	//Arshile Gorky
	{
		nomePintor:"Arshile Gorky",
		fotoPintor:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Archives_of_American_Art_-_Arshile_Gorky_-_3044.jpg/640px-Archives_of_American_Art_-_Arshile_Gorky_-_3044.jpg",
		textoPintor:[
			"Arshile Gorky (1904-1948), foi um pintor surrealista arménio pioneiro e a mais importante influência sobre os membros do movimento expressionista abstrato. O pintor passou a maior parte da sua vida como cidadão dos Estados Unidos. Junto com Mark Rothko, Jackson Pollock e Willem de Kooning, Gorky é considerado um dos mais importantes pintores norte-americanos do século XX. Como tal, especula-se que as suas obras são influenciadas pelo sofrimento e pela perda que o artista sofreu por causa do genocídio arménio.",
			"Gorky nasceu em 15 de abril de 1904, na aldeia de Khorgon, em Van Vilayet, no leste da Arménia. Aos cinco anos, começou a desenhar e a pintar. Por volta da mesma época, o seu pai emigrou para os Estados Unidos para evitar ser mobilizado para exército, deixando para trás a família na cidade de Van. Em 1915, Gorky fugiu de Van durante o genocídio armênio e escapou com sua mãe e suas três irmãs para um território controlado pela Rússia. Após o genocídio, a mãe de Gorky morreu de fome em Erevão em 1919. Quando chegou aos Estados Unidos, em 1920, Gorky, com 16 anos, juntou-se ao seu pai, mas nunca se deram bem.",
			"Gorky estudou na Technical High School de Providence até à primavera de 1921. Depois frequentou a New School of Design, em Boston, no ano de 1924, data da primeira sua pintura conhecida, <i>Park Street Church</i> (), assinada com o pseudónimo <i>Arshile Gorky</i>. O seu nome original era Vostanik Manoug Adoian. Porém como era hábito dos imigrantes na América, mudou o nome para Arshak Gorky. Arshak é um nome real da dinastia arsácida e Gorky significa <i>amargo</i> em russo. Mais tarde, adotou o nome Arshile, a versão caucásica do nome real Arshak. No processo de reinventar a sua identidade, Gorky teria afirmado ser um nobre da Geórgia e até mesmo dito às pessoas que era parente do grande escritor russo Maxim Gorky.",
			"Em 1925, Gorky mudou-se para Nova York, adquirindo o seu primeiro ateliê. Cinco anos depois participou na sua primeira exposição coletiva, <i>Exhibition of Work of 46 Painters and Sculptors under 35 Years of Age</i>, no Museu de Arte Moderna de Nova York. O artista teve sua primeira exposição individual em 1934, nas Mellon Galleries, em Filadélfia. Demorou vinte anos, pintando no estilo de Cézanne e depois no de Picasso, até chegar a seu estilo maduro evidente em <i>The Liver is the Cock's Comb</i> (O Fígado é a Crista do Galo, 1944). Na obra, tudo está em vias de se transformar em outra coisa. As forças biomórficas tem Miró como referência, enquanto a cor brilhante e o seu tratamento espontâneo refletem o entusiasmo do artista por Kandinsky. A força de atração e repulsão das formas e o seu interrelacionamento dinâmico, no entanto, são características exclusivamente suas.",
			"Gorky foi o personagem principal da transição entre o surrealismo norte-americano e o movimento que se seguiu nos Estados Unidos, o Expressionismo Abstrato. A sua obra inicial foi realizada em condições de extrema pobreza ainda na Arménia, mas já evidenciava uma progressão constante através dos estilos modernistas básicos. Durante a Primeira Guerra, começou a fazer explorações cada vez mais corajosas e, nos anos 1930, já buscava o surrealismo.",
			"Após dois anos de grande felicidade, 1943-1945, com o auge da produção artística, um novo casamento e o nascimento de dois filhos, a desgraça cai sobre Gorky. A crítica à sua exposição de 1945 foi dececionante: alguns acusaram-no de ser um mero seguidor da arte europeia. Em janeiro de 1946, o seu ateliê incendeia-se e Gorky perde os trabalhos em curso. Um mês mais tarde, fica a saber que sofre de um cancro do cólon. Os tratamentos deixam-no muito debilitado. A 26 de junho de 1948, fica gravemente ferido num acidente de viação que lhe paralisa o braço com que pinta. Alguns dias depois, a sua mulher, que tem um caso com o seu amigo Matta, abandona-o. Despedaçado física e moralmente, Arshile Gorky enforca-se no dia 21 de julho. O Whitney Museum organizará uma retrospetiva do artista em 1951.",
			"Harold Rosenberg, um dos principais críticos do Expressionismo Abstrato, diz que a obra de Gorky nessa época era <i>cheia de metáforas e associações,  entre organismos estranhos e macios e fendas e borrões insidiosos, pétalas que lembram garras numa selva de partes corporais flácidas, fístulas intestinais, genitálias e várias dobras nos membros</i>."
		],
		obrasPintor:[
			{
				nomeObra:"Park Street Church",
				anoObra:1924,
				fotoObra:"https://www.paintingmania.com/arts/arshile-gorky/large/park-street-church-boston-250_48460.jpg",
				textoObra:"Primeira obra conhecida de Gorky, então com 19 anos de idade, seguindo uma corrente impressionista."
			},
			{
				nomeObra:"The Artist with his Mother",
				anoObra:1936,
				fotoObra:"https://whitneymedia.org/assets/artwork/2171/50_17_cropped.jpeg",
				textoObra:"Gorky viveu permanentemente inquietado pela dolorosa saudade da mãe, morta de fome em 1919. Nesta pintura recria a sua recordação, a partir de uma fotografia, tirada em 1912, do artista, então com 8 anos, com a sua mãe. Vestida com roupas simples de campo, a sua mãe é uma figura distante e magra, com olhos notáveis e penetrantes. Gorky retratou-a com uma simplicidade clássica e cuidadosa, transformando a sua beleza sombria nas características perfeitas de um ícone da igreja do Leste Europeu."
			},
			{
				nomeObra:"Garden in Sochi",
				anoObra:1943,
				fotoObra:"https://uploads0.wikiart.org/images/arshile-gorky/garden-in-sochi.jpg!Large.jpg",
				textoObra:"Esta pintura (a primeira de seis sobre este tema) representa a reflexão nostálgica de Gorky sobre o jardim que fazia parte da fazenda do seu pai perto do Lago Van da sua Arménia natal. É notória a influência de Miró, em termos de paleta, composição e formas. Num texto datilografado entregue ao Museu de Arte Moderna, Gorky descreveu o jardim e os seus objetos (incluindo cenouras e porcos-espinhos), bem como os seus motivos retratados, incluindo mulheres esfregando seus seios em rochas para ver seus desejos cumpridos, e a <i>Árvore Sagrada</i> com pedaços rasgados de roupas de pessoas que visitam a árvore. <br /><br /> Na pintura é identificável a imagem central de um sapato elegante que o pai de Gorky supostamente lhe deu antes de deixar a Arménia. No entanto, o espectador que insiste em uma leitura muito específica das imagens de Gorky não será totalmente recompensado, pois o prazer maior é permitir que os seus títulos sugiram um assunto, e então permitir que as nossas próprias memórias e associações se misturem com o que está no tela de pintura. Nesse sentido, as suas obras permitem que o espectador se divirta no jogo lírico da cor, seguindo o ritmo das formas curvas enquanto elas nos ajudam a abrir as memórias de nossas próprias experiências que percebemos serem comuns a toda a humanidade."
			},
			{
				nomeObra:"Waterfall",
				anoObra:1943,
				fotoObra:"https://d3d00swyhr67nd.cloudfront.net/w1200h1200/collection/TATE/TATE/TATE_TATE_T01319_10-001.jpg",
				textoObra:"Esta pintura pertenca à fase em que Gorky se dedicou a produzir uma série de pinturas que se referem a formas naturais e rústicas. Este tema era perfeito para ele: a ideia de uma arte de sugestão e ocultação, de formas dissolvidas ou sobrepostas de perplexidades. Nesta pintura, formas amorfas e pingos de tinta líquida sugerem a fluidez de uma cascata. Mas, mesmo aqui, houve deliberação: uma flecha ostentada por uma figura reta (influência de Miró) aponta para baixo numa série de fluxos e obstruções, em que a paisagem se torna áspera e desmorona numa profusão gloriosamente desleixada. Ele escreveu: <i>Oposta a essa visão de destruição está a visão da criação, nas aparências que se dissolvem e se reformam</i>."
			},
			{
				nomeObra:"The Liver is the Cock's Comb",
				anoObra:1944,
				fotoObra:"https://uploads4.wikiart.org/images/arshile-gorky/the-liver-is-the-cock-s-comb.jpg!Large.jpg",
				textoObra:"O título altamente descritivo desta pintura representa definitivamente os sentimentos que Gorky está tentando transmitir. Mas também é mais sábio e menos sugestivo do que se imagina. À primeira vista, parece um vibrante, mas confuso, desenho animado da Disney. Mas, observando melhor, não vemos personagens divertidas na pintura. Existem curiosas formas fálico-sexuais, formas afiadas e algo que se parece com um ovo cozido. Esta pintura foi inspirada por uma fazenda na Virgínia, pertencente ao seu segundo casal de sogros. Gorky sempre sentiu uma proximidade com a natureza como uma fuga à dor do genocídio arménio e à morte da sua mãe. A pintura parece amarrar tudo num pequeno arco. Ele representa a sua terra natal (agora Turquia), a sua imigração para os EUA, a sua frustração sexual ao longo da sua vida e a paz que encontrou na natureza."
			},
			{
				nomeObra:"One Year the Milkweed",
				anoObra:1944,
				fotoObra:"https://images.fineartamerica.com/images/artworkimages/mediumlarge/3/one-year-the-milkweed-arshile-gorky.jpg",
				textoObra:"Camadas semitransparentes de tinta foram lavados de forma desigual na tela, e formas evocativas, mas indistintas, foram escovadas. Os tons verdes e castanhos sugerem uma paisagem, mas não há formas de paisagem identificáveis nem qualquer recessão espacial. Em vez disso, os gotejamentos verticais e a alternância de tons claros e profundos criam um efeito brilhante em toda a superfície da imagem. Inspirada por uma fazenda dos seus sogros, na Virgínia, a pintura poderia ser descrita como uma espécie de pastoral abstrata. A técnica solta de lavagem reflete o interesse de Gorky pelo procedimento surrealista do automatismo, que explorava efeitos aparentemente acidentais obtidos pela pintura e pelo desenho sem premeditação. Na teoria surrealista, esses efeitos acidentais eram vistos como reveladores dos processos inconscientes de pensamento. O título foi dado à pintura pelo amigo de Gorky, o grande poeta e teórico surrealista André Breton."
			},
			{
				nomeObra:"The Limit",
				anoObra:1947,
				fotoObra:"https://www.paintingmania.com/arts/arshile-gorky/large/limit-250_48473.jpg",
				textoObra:"O diversificado corpo de trabalho de Arshile Gorky foi crucial para o surgimento do expressionismo abstrato. Ele adotou as formas biomórficas dos pintores surrealistas, mas libertou ainda mais essas formas por meio do próprio processo de pintura, enfatizando cores mais líricas e conteúdo pessoal. Em <i>The Limit</i>, de 1947, ele torna-se mais minimalista e monocromático."
			},
			{
				nomeObra:"Untitled (Virginia Summer)",
				anoObra:1947,
				fotoObra:"https://files.ocula.com/anzax/ba/ba7b3633-019b-4396-b217-db30f04a7f84_1300_1112.jpg",
				textoObra:"<i>Untitled (Virginia Summer)</i> combina movimento e fluidez com memórias íntimas das suas férias, na década de 1940, em Crooked Run Farm, a propriedade rural da Virgínia, pertença dos seus sogros. Apaixonado por seu ambiente bucólico, Gorky produziu dezenas de desenhos <i>ao ar livre</i>, capturando as suas respostas primitivas à dinâmica do mundo natural que experimentou por meio de desenho automático e de associação livre. Com charme enigmático semelhante, o trabalho recém-descoberto sugere formas biomórficas e figuras que flutuam dentro e fora de uma paisagem vibrante, cheia de folhagem verde envolta e enterrada em um mar de azul nublado. As figuras animalescas aqui, representadas com olhos bulbosos vermelhos e amarelos e partes do corpo multicoloridas, são motivos recorrentes na obra de Gorky. Um exemplo excelente e bem preservado da poderosa originalidade e inventividade de Gorky, <i>Untitled (Virginia Summer)</i> ocupa seu lugar entre as obras mais comoventes da carreira do pintor."
			},
		]
	},
	//Jackson Pollock 
	{
		nomePintor:"Jackson Pollock",
		fotoPintor:"https://www.jackson-pollock.org/images/jackson-pollock.jpg",
		textoPintor:[
			"Jackson Pollock nasceu em Cody, no estado de Wyoming, EUA, em 1912. Era o mais novo de cinco irmãos e vinha de uma família sem grande segurança económica e social. Foi abandonado pelo pai aos 9 anos de idade, e mal tinha auxílio da mãe. Habituou-se a viver dentro de uma instabilidade emocional, mergulhado em sentimentos de medo, baixa auto-estima e insegurança, que se agravaram com a sua adolescência. Tinha um carácter indisciplinado e imprudente. Com o avançar dos anos, o problema do álcool, muito presente na sua vida, intensificou todas estas características da sua personalidade. No entanto, e apesar de todas as dificuldades pelas quais passava, sempre manteve o sonho de um dia vir a ser pintor.",
			"Em 1930, muda-se para Nova Iorque, e frequentou as aulas do pintor Thomas Hart Benton. Com ele, tomou conhecimento de alguns conceitos de composição e espaço. Conforme foi desenvolvendo os seus gostos artísticos, ganhou grande interesse por pintores muralistas mexicanos, como Diego Rivera, mas principalmente por David Siqueiros. Interessou-se, sobretudo, pelas técnicas utilizadas nas suas pinturas, tais como: <i>airbrushing</i>, <i>pouring</i> e <i>dripping</i>. Mais tarde, Pollock recebe algumas influências de pintores cubistas, como Pablo Picasso, e pós-cubistas como Joan Miró.",
			"Tudo mudou na vida de Pollock quando conheceu a sua mulher, a pintora Lee Krasner, e também quando a galerista Peggy Guggenhaim surgiu na sua vida. Peggy convidou-o para expor na sua galeria, e foi assim que começou a estar rodeado de pessoais mais influentes, artistas e pessoas dentro da elite artística, como o pintor Willem de Kooning, um cultor do movimento expressionista abstracto. O surrealismo também foi algo que lhe causou bastante influência em termos conceptuais.",
			"Na altura, o trabalho de Pollock estava exposto em galerias de arte em Nova Iorque, mas, mesmo assim, não atingiu o seu auge. O pico deu-se, em 1949, com as fotografias a preto-e-branco captadas por Hans Namuth, um fotógrafo alemão. ",
			"Jackson Pollock via a arte como um processo de auto-descoberta, de denúncia de medos intrínsecos e de fuga de sentimentos reprimidos. O pintor não pretendia representar, através da pintura, a época em que vivia. Pretendia, sim, ir além da representação de regimes totalitários frequentes na época, além da bomba atómica e da guerra civil. Afinal, cada época histórica tem tendência para encontrar a sua própria técnica. Diz-se que o Expressionismo Abstracto teve origem em dois acontecimentos marcantes, entre eles, a grande depressão financeira nos EUA, em 1929, e a Segunda Guerra Mundial.",
			"Pollock é uma figura central deste movimento, conhecido pela utilização da técnica <i>drip + painting = dripping</i>. <i>Dripping</i> é a técnica em que a tinta é lançada directamente sobre a superfície da tela. Ao contrário do que se pensa, o pintor era bastante perfeccionista, cada detalhe nos seus quadros era planeado. Cada traço, cada enquadramento, cada efeito cromático, tudo arquitectado ao pormenor. O pintor dava bastante importância à precisão pormenorizada da cor, da composição, textura, relevo e luz das suas pinturas. De seguida, decidiu largar a típica pintura em cavalete, e utilizou a tela estendida no chão. A isto chama-se <i>all over</i>. Com a tela no chão atirava tinta e com isso abandonava o tradicional pincel. A pintura no chão favorecia uma maior mobilidade corporal, permitindo o acesso aos quatro cantos da tela e estar dentro dela, sentindo-a.",
			"Com Pollock nasce a pintura de acção, <i>action painting</i>, onde o movimento, velocidade, e intensidade tomam a devida importância, para obter o resultado pretendido. Estes são tópicos primordiais para o minucioso trabalho do pintor. É aqui onde a questão da temporalidade se torna crucial para as suas pinturas, pois existe uma exploração espácio-temporal até aqui nunca tinha sido tão explorada, no mundo da pintura. Foi em 1947, que ocorreu esta mudança de conteúdo temático, e que se começou a repetir um padrão típico nas obras de Pollock, baseado no <i>dripping</i>. Cada gota de tinta ganhava um significado muito próprio e muito privado. Há quem não compreenda a intensidade de cada <i>drop</i>, e é certo que ninguém entenderá tão bem como ele entendia. De certa forma, as suas pinturas acarretam uma energia dinâmica que não nos permite ficar indiferentes a tais preciosidades.",
			"Pollock é o eterno pintor da melancolia. Porém, apesar das suas crises depressivas e existenciais, as suas telas manifestavam, por vezes, júbilo, contentamento e liberdade. Tudo relacionado com demonstrações do foro intimo com exclusão de factos exteriores. Era criada uma espécie de comunicação interna entre a viabilidade da arte e a viabilidade da vida."
		],
		obrasPintor:[
			{
				nomeObra:"The She Wolf",
				anoObra:1943,
				fotoObra:"https://www.jackson-pollock.org/images/paintings/the-she-wolf.jpg",
				textoObra:"<i>The She Wolf</i> é uma das obras mais conhecidas de Jackson no período pré-gotejamento (pre-dripping). Apareceu na sua primeira exposição individual em 1943 e, no ano seguinte, foi comprado pelo Museu de Arte Moderna, tornando-se na primeira pintura de Pollock a entrar numa coleção do museu. Embora Pollock nunca tenha confirmado isso, muitos pensam que a pintura é baseada na lendária mãe lobo de Rómulo e Remo, os gémeos que, segundo um mito, fundaram Roma. <i>The She Wolf</i> é considerado uma pintura importante no desenvolvimento da carreira artística de Pollock e um dos melhores exemplos de seu amor pela abstração de forma livre."
			},
			{
				nomeObra:"Mural",
				anoObra:1943,
				fotoObra:"https://www.jackson-pollock.org/images/paintings/mural.jpg",
				textoObra:"A obra <i>Mural</i> resultou de uma encomenda da famosa mecenas e colecionadora da arte, Peggy Guggenheim, de criar um quadro gigantesco (cerca 6,0 x 2,5 m) para cobrir uma parede inteira na entrada da sua nova casa. Ela mesmo mandou fazer a gigantesca tela e entregá-la no estúdio de Pollock, deixando-lhe a completa liberdade criativa para a obra. Conhecedora do trabalho de Pollock, Guggenheim estava ansiosa para apresentar na sua casa a nova corrente artística americana, o Expressionismo Abstrato, que ela estava a divulgar na sua galeria de arte. <br /><br /> Posteriormente à encomenda, em julho de 1943, Pollock assinou um contrato com a galeria Guggenheim para aí expor obras suas, em novembro do mesmo ano. Ele pretendia ter o mural pronto na data de inauguração da exposição. No entanto, à medida que o tempo se aproximava, a enorme tela do mural continuava em branco. Guggenheim começou a pressioná-lo. Pollock passou semanas olhando para a tela em branco, queixando-se aos amigos de que estava <i>bloqueado</i> e, realmente, parecia obcecado e deprimido. Finalmente, de acordo com todos os relatos, ele pintou a tela inteira, numa explosão frenética, de energia, por volta do dia de Ano Novo de 1944, embora a pintura tenha a data de 1943. Anos depois Pollock confidenciou a um amigo que teve uma visão: <i>Foi uma debandada de todos os animais do oeste americano, vacas, cavalos, antílopes e búfalos. Tudo está a correr naquela maldita superfície</i>. A suposta visão figurativa de Pollock pode ter sido uma evocação da sua infância no oeste americano. Embora possa haver algumas sugestões de figuração dentro do <i>Mural</i>, o seu impacto geral é o da abstração e da liberdade, relativamente às restrições impostas pelas figuras. <br /><br /> Enquanto os primeiros trabalhos de Pollock eram interpretações sombrias do regionalismo figurativo de Thomas Hart Benton, o <i>Mural</i> exibe um vigor expressionista abstrato. São muitas as influências da vida e dos estudos de Pollock presentes no <i>Mural</i>: os ritmos enérgicos de Benton, as cores rodopiantes do artista americano Albert Pinkham Ryder e até os negros ásperos do artista barroco espanhol El Greco. Também foi inspirado pelo trabalho do muralista mexicano Diego Rivera, bem como pela abstração quase figurativa do artista a quem Pollock mais deve, Pablo Picasso. Também podemos ver influências da sua psicanálise junguiana, da arte indígena americana que ele viu quando criança e da técnica surrealista do automatismo, que tentava abandonar o controlo consciente para permitir que a mente inconsciente guiasse a mão."
			},
			{
				nomeObra:"Full Fathom Five",
				anoObra:1947,
				fotoObra:"https://www.jackson-pollock.org/images/paintings/full-fathom-five.jpg",
				textoObra:"<i>Full Fathom Five</i> é uma das primeiras obras-primas da técnica de gotejamento (dripping) de Pollock. Ele criou as suas pinturas mais famosas durante o período de gotejamento (dripping) que durou de 1947 a 1950. A pintura por gotejamento (dripping) é uma forma de arte abstrata na qual a tinta é gotejada ou derramada na tela, em vez de ser cuidadosamente aplicada. Pollock esteve entre os pioneiros da técnica de gotejamento (dripping), devido ao que a revista TIME o apelidou de <i>Jack the Dripper</i>."
			},
			{
				nomeObra:"Number 5",
				anoObra:1948,
				fotoObra:"https://www.jackson-pollock.org/images/paintings/number-5.jpg",
				textoObra:"Trata-se da mais famosa e mais valiosa pintura de Jackson Pollock. Em novembro de 2006, foi recorde mundial de maior preço pago por uma pintura quando foi vendida a um comprador anónimo por 140 milhões de dólares. Em outubro de 2015, ocupava o quinto lugar na lista das pinturas mais caras já vendidas. Esta pintura é considerada como um dos maiores monumentos ao Expressionismo Abstrato."
			},
			{
				nomeObra:"Number 30 - Autumn Rhythm",
				anoObra:1950,
				fotoObra:"https://www.jackson-pollock.org/images/paintings/autumn-rhythm.jpg",
				textoObra:"1950 foi o ano de ouro para Jackson Pollock. Foi uma época em que ele estava no seu mais alto nível artístico e tinha dominado a técnica de gotejamento (dripping). Surpreendentemente, ele abandonou o estilo de gotejamento (dripping) no ano seguinte. O <i>Autumn Rhythm</i>, que foi originalmente intitulado <i>Number 30</i>, é uma de suas várias obras-primas do período de gotejamento (dripping). A pintura consiste em padrões caóticos de tinta preta, branca e castanha e é conhecida por não ter nenhum ponto focal, tornando-a igualmente significativa.<br /><br /> Com <i>Autumn Rhythm</i>, feito em outubro de 1950, o artista está no auge da sua criatividade. A tinta diluída foi aplicada a uma tela não esticada mas colocada no chão, em vez de apoiada num cavalete. Derramado, pingado, driblado, espalhado, sacudido e respingado, o pigmento foi aplicado da maneira mais heterodoxa. O artista também utilizou paus, espátulas, facas, enfim, tudo menos o instrumento tradicional do pintor para construir composições densas e líricas, compostas por intrincados novelos de linha. Não há um ponto central de foco, nenhuma hierarquia de elementos nesta composição total em que cada pedaço da superfície é igualmente significativo. O artista trabalhou com a tela plana no chão, movendo-se constantemente ao redor dela enquanto aplicava a tinta e trabalhava dos quatro lados."
			},
			{
				nomeObra:"Number 31",
				anoObra:1950,
				fotoObra:"https://www.jackson-pollock.org/images/paintings/one-number31.jpg",
				textoObra:"Este quadro foi pintado numa época em que Pollock já dominava a técnica de gotejamento (dripping) pela qual ele é mais conhecido. Ele foi pintado com a tela no chão, como era a norma para as pinturas de Pollock e está entre as maiores obras já criadas pelo artista. Os apreciadores de Pollock costumam referir este trabalho como a prova da extraordinária habilidade e destreza técnica do artista. É considerado por alguns como a maior pintura por gotejamento (dripping) de Pollock. Iniciado aproximadamente três anos após sua primeira pintura usando esta técnica, o trabalho é uma evidência da habilidade e proeza técnica do artista. Cordões caligráficos e circulares animam e energizam cada centímetro da composição, que parece se expandir visualmente, apesar de seu tamanho já enorme. Como fez com todas as suas pinturas por gotejamento, Pollock pintou o <i>Number 31</i> com a tela aberta no chão."
			},
			{
				nomeObra:"Number One - Lavender Mist",
				anoObra:1950,
				fotoObra:"https://www.jackson-pollock.org/images/paintings/lavender-mist.jpg",
				textoObra:"Uma exposição de 1945 na Galeria Pierre Matisse pode ter sido o que deu um novo ímpeto ao posterior desenvolvimento do formato linear de Jackson Pollock. Esta exposição, que teve um impacto importante na cena artística americana durante a guerra, consistia em pequenos guaches de Joan Miró, que tinham sido contrabandeados da França ocupada pelos alemães. Compostas por formas espalhadas semelhantes a desenhos animados conectadas por um fino rendilhado de linhas autónomas, essas obras foram designadas por Constelações, invocando uma metáfora estelar. Pollock declarou que Miró era o artista que ele mais admirava, além de Picasso. Alguns críticos de arte declararam categoricamente que Miró era o precursor mais direto do tipo de trabalho que Pollock começou a fazer mais tarde. <br /><br /> A pintura <i>Number One</i>, mais conhecida por <i>Lavender Mist</i>, incorpora o avanço artístico alcançado por Pollock entre 1947 e 1950. Foi pintado num antigo celeiro transforado em estúdio, ao lado de uma pequena casa no East End de Long Island, onde Pollock viveu e trabalhou desde 1945. A propriedade levava diretamente a Accabonac Creek, onde os pântanos e a linda luz aquosa foram uma fonte de inspiração para ele. <br /><br /> O método de Pollock foi baseado nas suas experiências anteriores com pingos e respingos de tinta em cerâmica, vidro e tela sobre cavalete. Ali, ele colocava uma grande tela no chão do celeiro do seu estúdio, quase cobrindo todo o espaço. Usando tintas de pintura de paredes, ele pingava, derramava e arremessava pigmentos de pincéis e de bastões ensopados enquanto caminhava ao redor das telas. Disse que era esta a sua forma de estar <i>dentro do seu trabalho</i>, mediando o seu processo criativo. Para Pollock, que admirava a pintura de areia dos índios americanos, era quase um ato ritual convocar teias de cor para as suas telas e torná-las equilibradas, completas e líricas. Tal como os antigos pintores rupestres, ele <i>assinou</i> <i>Lavender Mist</i> no canto superior esquerdo e no topo da tela com as impressões das suas mãos."
			},
			{
				nomeObra:"Convergence",
				anoObra:1952,
				fotoObra:"https://www.jackson-pollock.org/images/paintings/convergence.jpg",
				textoObra:"A pintura intitulada <i>Convergence</i> era uma colagem de cores espalhadas em uma tela que criava formas e linhas magistrais que evocavam emoções e confundiam a visão. Com as pinceladas de Pollock, ele conseguiu usar cores, linhas, texturas, luzes e formas contrastantes. Esta pintura é enorme e seu tamanho só pode ser realmente apreciado pessoalmente. Em 1964, a produtora de quebra-cabeças Springbok Editions lançou o puzzle <i>Convergence</i>, com 340 peças e inspirado na pintura de Pollock que eles promoveram como <i>o puzzle mais difícil do mundo</i>. O impacto da da obra <i>Convergence</i> de Pollock ficou evidente em 1965, quando centenas de milhares de americanos compraram esse puzzle. <br /><br /> O estilo de pintura de Jackson Pollock, exemplificado por <i>Convergence</i>, é um desenvolvimento importante e inovador na história da arte. Na época da pintura, os Estados Unidos levavam muito a sério as ameaças do comunismo e da guerra fria com a Rússia. A <i>Convergence</i> era uma personificação da liberdade de expressão, manifestada por Pollock, contra as restrições de liberdade e contra as sociedades opressivas. Era tudo o que a América representava, mas embrulhado num <i>pacote</i> confuso, mas profundo. A sociedade americana apreciou o estilo de Pollock, porque se opunha ao realismo social e aos gestos políticos ostensivos. O seu trabalho abstrato era difícil de decifrar, mas eram claramente evidentes, tanto a sua natureza rebelde como as suas expressões de liberdade."
			},
			{
				nomeObra:"Number 11 - Blue Poles",
				anoObra:1952,
				fotoObra:"https://www.jackson-pollock.org/images/paintings/blue-poles.jpg",
				textoObra:"A pintura intitulada <i>Blue Poles</i>, originalmente intitulado <i>Number 11</i>, é uma pintura expressionista abstrata e uma das obras mais famosas de Jackson Pollock. A pintura tornou-se uma das principais atrações da National Gallery of Australia, tanto pelo seu valor como uma obra importante do Expressionismo Abstrato da década de 1950, como pela sua importância na política e na história australianas. Porém, a sua aquisição e exibição na Gallery, em 1973, gerou polémicas na época. <br /><br /> Estando a obra à venda por 1,3 milhões de dólares, o então diretor da National Gallery of Australia, James Mollison, não podia autorizar a sua aquisição, porque, por lei, não podia autorizar aquisições acima de 1 milhão. Porém, o primeiro ministro da época, Gough Whitlam, assinou a autorização de aquisição, sujeitando-se a duras críticas de despesismo por parte da oposição conservadora que, em geral, desconsiderava o Expressionismo Abstrato. Porém, hoje, a autorização de aquisição da obra para a Gallery é considerada uma prova da grande sabedoria de Gough Whitlam. Além da enorme importância histórica e artística da obra, destaca-se a sua enorme revalorização financeira, estando atualmente cotada muito próximo dos 200 milhões de dólares. <br /><br /> Na época da criação da pintura, 1952, Pollock preferia não atribuir nomes às suas obras, mas sim números; como tal, o título original de <i>Blue Poles</i>, era simplesmente <i>Number 11</i>. Em 1954, o novo título <i>Blue Poles</i> foi visto pela primeira vez numa exposição na Sidney Janis Gallery. Supostamente, a redesignação teria sido proposta pelo próprio Pollock. Porém, esta suposição foi refutada pelo historiador de arte Dennis Phillips, que considerou o novo título como ambíguo e perturbador e que prestava um péssimo serviço à obra, porque nos leva a procurar os tais <i>pólos azuis</i> e limita o nosso campo de compreensão da pintura, no seu todo."
			},
			{
				nomeObra:"The Deep",
				anoObra:1953,
				fotoObra:"https://www.jackson-pollock.org/images/paintings/the-deep.jpg",
				textoObra:"Principalmente feito em preto e branco com algumas partículas de amarelo e de azul claro, <i>The Deep</i> é uma das obras mais famosas de Pollock após os gloriosos anos 1947-1950. É um trabalho importante do Expressionismo Abstrato. Os espectadores e críticos de arte discorrem sobre várias interpretações filosóficas desta pintura. O nome da pintura aumentou o seu mistério com várias deduções, como se ela representasse a profundidade em que reside o verdadeiro <i>eu</i> que cada pessoa esconde em si, mas que muito teme ter que enfrentá-lo. <br /><br /> Há evidências de que Pollock terá recebido inspiração de uma declaração de  Wassily Kandinsky no seu livro <i>On the Spiritual in Art</i>: <i>Não foi à toa que o branco foi escolhido como vestimenta de pura alegria e pureza imaculada. E o preto como vestimenta do maior e mais profundo luto e como símbolo da morte. O equilíbrio entre essas duas cores, obtido pela mistura mecânica, forma o cinza. Naturalmente, uma cor que surgiu dessa maneira não pode ter nenhum som externo, nem exibir qualquer movimento. O cinza é sem tom e imóvel. Essa imobilidade, no entanto, tem um caráter diferente da tranquilidade do verde, que é o produto de duas cores ativas e fica a meio caminho entre elas. O cinza é, portanto, a desconsolada falta de movimento. Quanto mais profundo se torna esse cinza, mais o elemento desconsolado é enfatizado, até se tornar sufocante.</i>."
			},
		]
	},
	//Franz Kline
	{
		nomePintor:"Franz Kline",
		fotoPintor:"https://upload.wikimedia.org/wikipedia/en/1/17/Franz_Kline_headshot.png",
		textoPintor:[
			"Franz Kline é uma figura chave do Expressionismo Abstrato, bem conhecido pelas suas pinturas em preto e branco, e fez uma contribuição poderosa para o movimento de vanguarda. Nascido na Pensilvânia em 1910, Kline desenvolveu um interesse pela ilustração durante o ensino médio e continuou a sua educação como desenhista na Universidade de Boston, entre 1931 e 1935. Continuou os seus estudos em Londres, retornando aos Estados Unidos em 1939.",
			"Kline mudou-se então para Nova Iorque, onde foi feita a sua carreira. O seu domínio precoce do desenho, incluindo a caricatura, conferiu-lhe a sintonia com a essência abstrata da linha. Trabalhando com óleo, o estilo de Kline foi desenvolvido a partir de obras figurativas e representacionais para composições emblemáticas e caligráficas, onde as formas rapidamente se tornaram marcas escovadas. O ambiente de Nova Iorque inspirou Kline; os seus esboços, óleos e murais pintados em 1940 para o Cedar Bar em Greenwich Village (um popular ponto de encontro dos expressionistas abstratos) revelam o seu interesse em buscar um equivalente pictórico dos ritmos dinâmicos da cidade, em pinceladas rápidas, enérgicas e largas.",
			"Observador atento da pintura de Willem De Kooning e de Robert Motherwell, em 1946, Kline começou a generalizar os seus temas, criando composições que enfatizavam a linha caligráfica. Estudos em tinta sobre papel reforçaram o gosto do artista por uma paleta reduzida a preto e branco. Quando o seu amigo De Kooning ampliou esses esboços, em 1948, com a ajuda de um projetor Bell-Opticon, proporcionou a Kline apreciar os seus traços ampliados em poderosos gestos abstratos. Isso confirmou a sua consciência do potencial dramático e expressivo do esboço, mas projetado numa escala monumental. Usando uma paleta limitada de preto em linhas grossas e ásperas pintadas com pincéis de pintor de paredes grandes em solo branco, Kline atingiu a maturidade do seu estilo próprio em 1950. Nesse mesmo ano, Kline garantiu a sua primeira exposição individual na Charles Egan Gallery em Nova Iorque, exibindo obras com pinceladas negras enormes em bandas e cunhas negrito, dominando as grandes telas brancas. ",
			"Embora alguns críticos acreditassem que os padrões da grade negra de Kline eram improvisações ampliadas de signos e símbolos encontrados na caligrafia oriental, o artista negou qualquer influência do Oriente no desenvolvimento de suas abstrações e enfatizou o seu fascínio pela beleza urbana de Nova Iorque. Embora Kline seja identificado principalmente com os seus trabalhos em preto e branco, ele também era um colorista distinto; os anos em preto e branco do pós-guerra deram lugar a explorações em cores. Os trabalhos de Kline tiveram um papel importante na definição do expressionismo abstrato, e o sucesso de seu estilo maduro influenciou muitos expressionistas abstratos de segunda geração.",
			"Durante a década de 1950, Kline ensinou em várias instituições, incluindo o Black Mountain College, na Carolina do Norte, e o The Pratt Institute, em Brooklyn. Em 1958, ele foi incluído na principal exposição do Museu de Arte Moderna, <i>The New American Painting</i>, que percorreu oito cidades europeias. O seu trabalho faz parte de importantes coleções públicas e privadas nos Estados Unidos, Canadá, Europa e Japão. A morte tragicamente prematura de Kline de uma doença cardíaca reumática, em 1962, deixou incerta a continuação da sua visão artística, porém, ele continua sendo um reconhecido mestre do Expressionismo Abstrato."
		],
		obrasPintor:[
			{
				nomeObra:"Chief",
				anoObra:1950,
				fotoObra:"https://www.sartle.com/media/artwork/chief-franz-kline.jpg",
				textoObra:"Os comentários dos críticos sobre as imagens do espetáculo inovador da pintura de Kline, em 1950, estabeleceram o padrão para posteriores revisões com a sua variedade de analogias. <i>Chief</i> era o nome de uma locomotiva que Kline recordava da sua infância, e é possível ler a imagem como uma reminiscência sensorial da sua potência, do seu som e da máquina a vapor. Alguns também acreditavam que a obsessão do artista com o preto estava ligada à sua infância passada numa comunidade de mineração de carvão dominada pela indústria pesada. Muitos já observaram, no entanto, que as formas nessas abstrações iniciais parecem ter evoluído a partir dos desenhos de Kline sobre a sua esposa, Elizabeth. Ele fez vários esboços dela sentada numa cadeira de balanço nos anos em que ela começou a sucumbir à doença mental; as formas circulares em <i>Chief</i> são comparadas com os círculos em branco representando o rosto dela nos desenhos."
			},
			{
				nomeObra:"Painting No. 7",
				anoObra:1952,
				fotoObra:"https://www.guggenheim.org/wp-content/uploads/1952/01/54.1403_ph_web-1.jpg",
				textoObra:"Ao contrário de seus colegas Pollock e De Kooning, Kline nunca experimentou elementos figurativos no seu trabalho maduro. Este é um bom exemplo dos seus trabalhos em preto e branco. A geometria rígida das linhas pretas amplas define a composição, talvez manifestando a sua reconsideração das pinturas icónicas de quadrados de Kazimir Malevich."
			},
			{
				nomeObra:"Black Reflection",
				anoObra:1956,
				fotoObra:"https://arthur.io/img/art/jpg/00017344bbe5ff5cd/franz-kline/black-reflections/large/franz-kline--black-reflections.jpg",
				textoObra:"<i>Black Reflection</i> é um exemplo das primeiras tentativas de Kline de introduzir a cor de volta às suas obras. O tratamento da cor nesta composição pode estar relacionado com as pinturas contemporâneas de Willem de Kooning e Hans Hofmann. O ponto focal desta imagem é a forma negra que Kline já tinha usado anteriormente em outras composições. Este fato atesta ainda mais a cuidadosa consideração que os artistas da <i>Action Painting</i> dedicaram às formas pictóricas nas suas composições."
			},
			{
				nomeObra:"Mahoning",
				anoObra:1956,
				fotoObra:"https://whitneymedia.org/assets/image/616601/large_kline.jpg",
				textoObra:"O que faz com que o preto e branco de Kline seja tão especial é que eles não são apenas consistentes, alguns até os chamam de pinceladas pretas violentas, agressivas em telas brancas. Os dois elementos são essenciais para a existência um do outro. Em vez de se concentrar nas áreas brancas como o “espaço negativo”, ele as pintou em ordem alternada com igual consideração. Kline criaria judiciosamente estudos de pequena escala para cada uma de suas pinturas finais sobre tela. Ele costumava pintá-los em jornais do tamanho de um cartão postal, trabalhando e refazendo cada gesto para obter o equilíbrio perfeito. Então, uma vez terminada a composição, Kline projetou-a em uma tela grande e repetiu o processo, com toda a sua intensidade."
			},
			{
				nomeObra:"Four Square",
				anoObra:1956,
				fotoObra:"https://uploads8.wikiart.org/images/franz-kline/four-square-1956.jpg!Large.jpg",
				textoObra:"É um exemplo da experimentação de Kline com composições angulares. Embora aparentemente estruturado na sua rigidez composicional, <i>Four Square</i> é um bom exemplo de sua abordagem gestual à pintura. O espectador é levado a refletir sobre a tela, visto como um close-up de um símbolo linguístico ou, talvez, um conjunto de janelas abertas. Neste trabalho, Kline também está tentando construir uma composição abstrata tridimensional, enquanto a maioria dos expressionistas abstratos preferiu o tratamento bidimensional da superfície pictórica. Kline alcança o efeito visual de profundidade através de justaposições energéticas de linhas verticais e horizontais e sua sobreposição diagonal."
			},
			{
				nomeObra:"Meryon",
				anoObra:1960,
				fotoObra:"https://media.tate.org.uk/art/images/work/T/T00/T00926_10.jpg",
				textoObra:"Existe um forte sentido arquitetónico em sua composição desta obra. A inspiração foi possivelmente uma gravação de uma torre do relógio do artista francês do século XIX Charles Meryon. Novamente, Kline representa não o objeto em si, mas a sua visão dele. Aparentemente espontânea no seu arranjo, esta composição foi concebida através de uma série de estudos preliminares, lançando uma nova luz sobre a natureza da sua técnica gestual."
			},
			{
				nomeObra:"Probst I",
				anoObra:1960,
				fotoObra:"https://cdn2.oceansbridge.com/2017/08/10141723/Probst-I-1960-Franz-Kline-oil-painting-1-768x1029.jpg",
				textoObra:"Esta obra refere-se a Jack Probst, um colega artista que morava perto de Kline em Greenwich Village. À primeira vista, essa composição é típica do seu trabalho em preto e branco. No entanto, há mais cores presentes nesta tela. Há salpicos de salmão amarelo e pálido que iluminam a solidez de formas negras e torcidas, criando efeitos luminosos e quentes. <i>Probst I</i> é um exemplo do trabalho tardio de Kline, onde ele voltou a empregar uma paleta mais ampla."
			},
		]
	},
	//Mark Rothko
	{
		nomePintor:"Mark Rothko",
		fotoPintor:"https://www.mark-rothko.org/images/Mark-Rothko-Photo.jpg",
		textoPintor:[
			"Embora tenha nascido na Letónia, Mark Rothko é um dos artistas americanos mais conhecidos, pelas peças expressionistas abstratas que ele criou durante o curso de sua carreira. Nascido em 1903, ele e a sua família emigraram para os EUA quando ele tinha 10 anos de idade. Algumas das obras pelas quais ele é mais conhecido são imagens que apresentavam grandes blocos de cores luminosas. Ele também é mais conhecido como um dos melhores pintores da Escola de Abstração de Nova Iorque, pelas formas, figuras e grande criação de cores que ele entregou, nas muitas pinturas que ele criou. As impressões de Mark Rothko são atualmente algumas das mais procuradas por consumidores de reproduções de arte em todo o mundo, destacando como a reputação desse artista se espalhou através de fronteiras geográficas e sociais.",
			"Em 1921, Mark Rothko frequentou a Universidade de Yale, com um projeto de estudos de obter um diploma, ou em engenharia, ou em direito. Porém acabou por abandonar ambas as rotas e escolheu uma carreira diferente. Depois de deixar Yale, Rothko mudou-se para Nova Iorque, como ele disse, <i>para vagabundear e passar um pouco de fome</i>. Nos seguintes, ele teve vários empregos e estudou algum tempo na Art Students League, sob o comando de Max Weber, um dos únicos professores que tinham conhecimento e entusiasmo pelo modernismo europeu. As primeiras pinturas de Mark Rothko foram orientadas para temas sociais e contêm conotações expressionistas e surrealistas. Refletiam a influência de Weber e também de artistas modernos, como Manet, Paul Cezanne e Picasso e mostraram o seu potencial como artista. As cenas urbanas e as paisagens e a aplicação grosseira da pintura mostraram um lado expressivo da arte que ele criaria mais tarde, e as características que o tornaram mais conhecido durante o curso de sua carreira como artista.",
			"Em meados da década de 1930, Mark Rothko juntou-se a um grupo de pintores em Nova Iorque, conhecido como <i>Os Dez</i>. Este grupo dedicava-se a trabalhos modernistas e, depois, ao trabalho abstrato que se seguiria e que foi extremamente popular neste período e durante várias décadas nos EUA. Faziam parte desse grupo, além de Mark Rothko, outros artistas, como, para citar alguns, Adolph Gottlieb, Louis Harris, Ben-Zion e Joseph Salmon.",
			"Durante a década de 1940, Mark Rothko adotou uma abordagem da arte, na qual ele queria mudar o que o público americano passara a conhecer como arte abstrata. Ele procurava uma nova linguagem para mostrar as diferentes visões americanas durante a guerra. Durante este período, muitas das peças que ele criou foram simbólicas da guerra e da vida americana dessa época. As características simbólicas crescentes incluíam formas biomórficas que foram usadas na sua arte, e foram influenciadas por imagens surrealistas e por artistas que estavam surgindo durante este período.",
			"No final dos anos 1940 e início dos anos 50, Mark Rothko criou algumas das peças pelas quais ele é mais conhecido na sua carreira. Muitas das obras que ele mostrou durante esse período mostraram pinceladas grandes e escuras, grandes blocos de cor e uma vasta variedade de lavagens. Criou peças grandes e contemplativas que simbolizavam, tanto a vida americana durante esse período, como as mudanças no mundo da arte e o trabalho abstrato que is surgindo, à medida que a sua carreira progredia.",
			"No final da década de 1950, Mark Rothko adotou outra abordagem para as suas obras. Eram frequentemente usadas cores e tons mais escuros e texturas mais ricas. Durante esse período, o artista também passou um bom tempo focado num trabalho que ele criaria para uma capela (Rothko Chapel) localizada em Houston. Isso não apenas demonstrou a crença numa arte espiritual, mas também a sua religiosidade. Mostrou os laços espirituais e emocionais entre a arte e a fé.",
			"Ao longo de sua vida, Mark Rothko sofreu com profundos episódios de depressão, e em 1970 ele tirou a própria vida, como muitos outros artistas tinham feito antes dele. Mas, mesmo com uma carreira mais curta do que muitos outros artistas no mundo abstrato, ele teve sucesso com os trabalhos que criou durante o curso de sua carreira. Quando faleceu, Mark Rothko teve uma exposição exclusiva, com algumas de suas peças mais famosas, no Museu Museu de Arte Moderna de Nova Iorque. Mark Rothko também foi visto como um dos principais artistas americanos, no mundo da pintura abstrata. Ele fez a transição para a arte abstrata e para novas abordagens modernas, que permaneceriam em vigor por várias décadas."
		],
		obrasPintor:[
			{
				nomeObra:"Entrance to Subway",
				anoObra:1938,
				fotoObra:"https://arthive.net/res/media/img/oy800/work/b79/50310@2x.jpg",
				textoObra:"Este trabalho figurativo inicial demonstra o interesse de Rothko pela vida urbana contemporânea. As características arquitetónicas da estação são recriadas superficialmente, incluindo as catracas e a letra 'N' na parede. Embora o humor das imagens seja suavizado pela influência do impressionismo, reflete muitos dos sentimentos do artista em relação à cidade moderna. A cidade de Nova Iorque era considerada desalmada e desumana, e algo disso é transmitido aqui pelas características anónimas e difusamente reproduzidas das figuras."
			},
			{
				nomeObra:"Slow Swirl at the Edge of the Sea",
				anoObra:1944,
				fotoObra:"https://uploads1.wikiart.org/images/mark-rothko/slow-swirl-at-the-edge-of-the-sea(1).jpg!Large.jpg",
				textoObra:"É um exemplo representativo do período surrealista de Rothko. A influência de Miró é clara. Toda a composição de cores suaves, estranhas figuras translúcidas, linhas horizontais, ângulos e redemoinhos, criam uma imagem vibrante mas velada de uma obscura paisagem primitiva. Pintada enquanto Rothko cortejava Mary Beistel, que se tornaria na sua segunda esposa, esta cena caprichosa também pode ser interpretada como um romance dentro de um mundo mítico e mágico, onde as figuras estão apreciando o oceano sobre um colorido amanhecer estampado no horizonte."
			},
			{
				nomeObra:"No. 9",
				anoObra:1947,
				fotoObra:"https://uploads0.wikiart.org/images/mark-rothko/no-9-1947.jpg",
				textoObra:"É um dos onze quadros que Rothko apresentou na Betty Parsons Gallery na primavera de 1949. Tendo deixado para trás as figuras e as paisagens do seu trabalho anterior, os <i>multiformes</i>, dos quais este é um exemplo típico, apresentavam formas borradas criadas a partir de camadas de tinta. O trabalho antecipa o avanço de Rothko, a partir de 1949, para os chamados <i>seccionais</i>. Os vermelhos quentes, laranjas e amarelos deste quadro são interrompidos pela estranha massa negra que vem da esquerda, bem como os redemoinhos de azul na parte inferior. As bordas borradas, os blocos de cores separadas e os registros iniciais retangulares podem ser vistos, bem como algumas experiências com tamanho e escala. Longe de ser apenas formas abstratas, Rothko acreditava que esses motivos eram objetos imbuídos da sua força vital, <i>organismos com a paixão pela auto-expressão</i>."
			},
			{
				nomeObra:"White Center (Yellow, Pink and Lavender on Rose)",
				anoObra:1950,
				fotoObra:"https://artsdot.com/ADC/Art-ImgScreen-2.nsf/O/A-8BWUHU/$FILE/Mark-rothko-marcus-rothkowitz-white-center.Jpg",
				textoObra:"Esta obra constitui a primeira manifestação séria do estilo multiforme de Mark Rothko, de vários blocos de cores complementares em camadas numa grande tela, em que Rothko continuou a simplificar os elementos de composição de suas pinturas. Em 1950, ele começou a dividir a tela em faixas horizontais de cor. Apesar da composição frontal e da ausência de ilusionismo espacial nesses trabalhos, as amplas faixas de cor aparecem simultaneamente a flutuar em frente ao plano da imagem e a fundir-se com o campo de cor sobre o qual elas são colocadas. Uma luminosidade resulta da estratificação repetida de finas lavagens de tinta, o que permite que algumas camadas inferiores se mostrem através das camadas superiores. Em cada obra desse período, Rothko buscava subtis variações de proporção e cor, conseguindo uma ampla gama de emoções e de humores. Em 2007, o quadro foi comprado por 72,84 milhões de dólares, pela família real do Qatar."
			},
			{
				nomeObra:"No. 1 (Royal Red and Blue)",
				anoObra:1954,
				fotoObra:"https://upload.wikimedia.org/wikipedia/en/4/4c/No_1_%28Royal_Red_and_Blue%29_by_Mark_Rothko_%281954%29.jpg",
				textoObra:"Este quadro, pintado em 1954, uma época considerada por muitos como o auge da veia criativa de Rothko, é considerado como uma das grandes realizações da pintura abstrata de Rothko. A aura estonteante da brilhante superfície vermelha e laranja é soberbamente contra-atacada pela pilha azul de intensa vividez na sua base, dando ao espectador a sensação de que a tela é iluminada por dentro. Esta pintura é um marco fundamental na fase madura da expressão artística de Rothko, na qual ele foi pioneiro em territórios sem precedentes de um espetacular derramamento de inovação."
			},
			{
				nomeObra:"Untitled (Yellow and Blue)",
				anoObra:1954,
				fotoObra:"https://www.markrothko.org/Untitled%20(Yellow%20and%20Blue)%20Mark%20Rothko.jpg?ezimgfmt=rs:400x521/rscb1/ngcb1/notWebP",
				textoObra:"No auge da criatividade simplificadora de Rothko no período dos chamados trabalhos <i>seccionais</i>, este quadro surpreende-nos uma aurora brilhante de luz e de cor cintilante e confronta-nos com a intensidade filosófica do seu criador, onde ele encenou algumas das mais comoventes, transcendentes e simplesmente impressionantes uniões já realizadas entre o material e o suporte, na grande tradição de tinta a óleo sobre tela. O quadro foi vendido a um anónimo por 46,5 milhões de dólares num leilão da Sotheby's em Nova Iorque."
			},
			{
				nomeObra:"Orange and Yellow",
				anoObra:1956,
				fotoObra:"https://uploads2.wikiart.org/images/mark-rothko/orange-and-yellow(1).jpg",
				textoObra:"<i>Orange and Yellow</i> reflete o estilo maduro de Mark Rothko, no qual dois ou três retângulos são colocados dentro de um fundo que os envolve e divide suavemente uns dos outros. As bordas dos retângulos nunca são distintas, evitando uma quebra ótica e permitindo que os olhos do espectador se movam silenciosamente de uma área para outra de forma contemplativa. Rothko não queria que pensássemos nele quando olhássemos as suas pinturas, então ele tentou remover todas as evidências do processo de criação. Para conseguir isso, ele aplicou várias camadas de tinta fina com pincel ou pano em telas não preparadas, que absorveram as cores em seu tecido. As muitas aguadas finas ajudam a dar leveza e brilho às suas pinturas, como se brilhassem por dentro."
			},
			{
				nomeObra:"Four Darks in Red",
				anoObra:1958,
				fotoObra:"https://wahooart.com/Art.nsf/O/8BWU7X/$File/Mark-Rothko-Marcus-Rothkowitz-Four-Darks-in-Red.jpg",
				textoObra:"É uma das dez obras de Rothko exibidas em 1969 na Galeria Sidney Janis. Com a sua paleta escura e restrita, a pintura exemplifica a gravitação do período tardio de Rothko em direção aos vermelhos e castanhos. Nesta obra Rothko estabeleceu um protótipo para a paleta roxo ou vermelho escuro, castanho e preto e para a composição horizontal que ele usaria mais tarde em diversos outros trabalhos, como a <i>Rothko Chapel</i>, por exemplo. Rothko acreditava que os retângulos apenas ofereciam uma nova maneira de representar as presenças ou espíritos que ele tentava capturar e imaginou uma espécie de comunhão direta entre ele e o espectador, em que este seria tocado por uma espiritualidade mais elevada."
			},
			{
				nomeObra:"No. 11",
				anoObra:1963,
				fotoObra:"https://uploads6.wikiart.org/images/mark-rothko/no-11.jpg!Large.jpg",
				textoObra:"As obras de Rothko geralmente são caracterizadas por retângulos ou formas orgânicas de cores vibrantes e intensas, com o objetivo de evocar uma resposta emocional no espectador. Ele procurava criar uma experiência sensorial por meio do uso cuidadoso da cor e da forma. As suas pinturas muitas vezes parecem desprovidas de figuras ou objetos identificáveis, permitindo que o observador mergulhe nas emoções sugeridas pelas composições cromáticas. Esta obra <i>No. 11</i>, é uma das suas últimas cintilações luminsas, nos amarelos, laranjas e cor de pêssego, num período em que na paleta de Rothko já habitavam as cores escuras e depressivas."
			},
			{
				nomeObra:"Rothko Chapel",
				anoObra:1965,
				fotoObra:"https://media.timeout.com/images/103204320/750/422/image.jpg",
				textoObra:"Situada no campus da St. Thomas Catholic University, a capela Rothko foi financiada por John e Dominique de Menil e contém catorze pinturas murais de Rothko. Existem três trípticos e cinco trabalhos individuais. Todas estas pinturas são em tons de roxo ou vermelho escuro, castanho e preto e são de grande escala. Rothko trabalhou em estreita colaboração com os arquitetos, tendo o controlo quase completo sobre a forma do edifício e do seu ambiente interior de meditação. A escuridão das obras pode ser vista como melancólica e expressiva do humor de Rothko nos seus últimos anos. Infeizmente para ele, não viveu para assistir à inauguração da Capela."
			},
			{
				nomeObra:"Untitled (Blue Divided by Blue)",
				anoObra:1966,
				fotoObra:"https://uploads8.wikiart.org/images/mark-rothko/untitled-blue-divided-by-blue-1966.jpg!Large.jpg",
				textoObra:"<i>Blue Divided by Blue</i> de 1966 é uma pintura rara de Mark Rothko, considerada uma das quatro únicas obras gravadas em papel deste ano de 1966. Neste caso, o papel foi montado sobre tela. Rothko dedicou-se, até 1970, a explorar os limites da pintura sobre papel. Num período de depressão, <i>Blue Divided by Blue</i> é sem dúvida uma das suas pinturas que aparenta mais serenidade."
			},
			{
				nomeObra:"Untitled, Black on Gray",
				anoObra:1969,
				fotoObra:"https://www.mark-rothko.org/images/paintings/untitled-black-on-grey.jpg",
				textoObra:"Rothko juntou muitos conhecidos seus da elite mundial da arte nova-iorquina no seu estúdio para mostrar o seu último quadro, que marcaria a sua última série de pinturas, a <i>Black on Grays</i>. O evento foi principalmente envolto em silêncio, porque alguns pensaram que estas eram premonições de sua morte. Outros achavam que, com a prevalência de imagens lunares na cultura popular, eram interpretações de paisagens lunares. Outros achavam que eram pinturas de visões noturnas. O grupo de convidados não levava a sério a apresentação, o que era devastador para Rothko, pois, além do mais, afirmavam que só ele sentia o mundo interior das suas pinturas e que, assim, elas eram apenas compreensíveis para ele sozinho. Os <i>Black on Grays</i> foram pintados diretamente sobre tela branca e não tinham a pintura base normal que Rothko gostava de ter por baixo. Trabalhando apenas em dois registos, ele restringiu severamente as cores e reduziu a tela a um tamanho mais acessível e intimista. O contraste extremo da luz e da escuridão evoca uma tristeza que se desenrola como um drama psicológico, tanto mítico como trágico."
			},
		]
	},
	//Adolph Gottlieb
	{
		nomePintor:"Adolph Gottlieb",
		fotoPintor:"https://static.wixstatic.com/media/f4938a_89870c95ff6a483ba3e057ca4a01dbcf~mv2.jpg/v1/fill/w_260,h_310,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/Gottlieb%202.jpg",
		textoPintor:[
			"Adolph Gottlieb foi um proeminente pintor americano e membro da primeira geração de expressionistas abstratos. Através de um uso idiossincrático da abstração com pictogramas e símbolos mitológicos, as suas obras alcançaram uma intensidade emocional através da cor e da linha. <i>Hoje, quando as nossas aspirações foram reduzidas a uma tentativa desesperada de escapar do mal e os nossos tempos estão desarticulados, as nossas imagens obsessivas, subterrâneas e pictográficas são a expressão da neurose que é a nossa realidade</i>, refletiu ele certa vez. <i>Na minha opinião, a chamada abstração não é abstração. Pelo contrário, é o realismo do nosso tempo</i>.",
			"Nascido em 14 de março de 1904, em Nova Iorque. Após abandonar o ensino médio em 1919, Gottlieb participou da Art Students League brevemente antes de partir para a Europa em 1921. Ele viajou para Viena, Berlim, Dresden e Munique, tendo participado em aulas de desenho ao vivo em Paris. Logo após seu retorno em 1922, ele estudou na Art Students League de Nova Iorque, onde conviveu com um grupo de pintores que incluía Mark Rothko, Lou Schanker, Barnett Newman, e John Graham. Gottlieb, tal como Rothko, também começou a produzir obras influenciadas pela figuração estilizada de Milton Avery. Interessado em Surrealismo, o trabalho de Gottlieb tornou-se mais abstrato, pois incorporou na sua prática o desenho automático e as teorias psicológicas de Sigmund Freud e Carl Jung.",
			"Gottlieb fez sua primeira apresentação individual na Galeria Dudensing em 1930. Em 1935, tornou-se um dos membros fundadores do <i>The Ten</i>, um grupo de artistas que se opunha ao estreito realismo dos pintores regionalistas contemporâneos. Depois de outra viagem à Europa em 1935, Gottlieb trabalhou num projeto federal de artes entre 1936 e 1937. Como muitos de seus colegas, ele era politicamente ativo, juntou-se à Artist's Union em 1936 e tornou-se membro fundador do American Artist's Congress nesse mesmo ano e da Federação de Pintores e Escultores Modernos em 1940.",
			"Durante uma viagem ao Arizona (1937-1938), ele viu exemplos de murais arcaicos em regiões índias, o que, conjuntamente com a influência emergente do surrealismo em Nova York durante a Segunda Guerra Mundial o levou a repensar sua arte. Em 1941, começou a fazer os seus pictogramas, imagens compostas de formas inventadas e misteriosas, dispostas numa grade no plano da imagem, sugerindo a comunicação simbólica das culturas pré-históricas. Os pictogramas de Gottlieb também demonstram seu fascínio pela arte primitiva que o levou a colecionar arte africana, a partir do final dos anos 1930 e a frequentar regularmente exposições de arte africana, indígena e pré-histórica no Museu de Arte Moderna. Ele via a arte primitiva como a expressão direta e incisiva de forças desconhecidas e uma fonte relevante de significado no meio do tumulto e da injustiça dos eventos da Segunda Guerra Mundial.",
			"Em 1947, Gottlieb entrou para a Kootz Gallery e associou-se com Robert Motherwell e Hans Hofmann. Dividindo seu tempo entre Nova Iorque e Provincetown, ele participou, no início dos anos 50, em discussões e fóruns sobre desenvolvimentos artísticos americanos. Nas suas pinturas dos anos 50 e 60, que apresentavam formas abstratas em grande escala flutuando no plano do quadro, Gottlieb revelou o seu crescente interesse pela pintura em cores primárias e pelo simbolismo abstrato.",
			"Na década de 1960, ele começou a produzir algumas de suas obras mais famosas, coletivamente conhecidas como <i>Burst Paintings</i>, cujo motivo comum é um círculo parecido com o sol que paira sobre marcas caligráficas. Várias comissões e prémios, incluindo uma retrospectiva em 1968 realizada simultaneamente nos museus Whitney e Guggenheim em Nova Iorque, destacaram o fim da carreira de Gottlieb. Depois de sofrer um derrame cerebral em 1971, Gottlieb morreu a 4 de março de 1974, em Nova Iorque."
		],
		obrasPintor:[
			{
				nomeObra:"Pictograph",
				anoObra:1946,
				fotoObra:"https://buffaloakg.org/sites/default/files/styles/fixed_height_medium/public/artwork/1976_001_001_o2.jpg",
				textoObra:"Esta pintura consiste em uma estrutura de grade solta dentro da qual são fragmentadas e sobrepostas formas femininas que foram abstraídas em linhas e formas planas. Espirais adicionais e formas geométricas, assim como rabiscos e uma flecha (que podem sugerir elementos masculinos ou o caminho que leva para fora da estrutura e do confinamento) preenchem o restante espaço da imagem. Os estudiosos frequentemente apontam para as cores rosa e castanho como a influência remanescente das cores que o artista absorveu durante sua visita ao Arizona, embora se possa facilmente apontar para influências de Willem de Kooning, ou de André Masson, por exemplo. Defensor da honestidade das duas dimensões, contra a pretensa ilusão da profundidade (terceira dimensão) no suporte plano, Gottlieb afirmava que, embora a abstração geométrica reduzisse a pintura a um exercício puramente intelectual, essa arte deveria ser uma expressão do pensamento e da experiência humana. Assim, nesta pintura há uma textura macia e pictórica na superfície que humaniza a geometria, comunicando ao observador o significado da nossa própria existência pessoal dentro da humanidade, como um todo."
			},
			{
				nomeObra:"Vigil",
				anoObra:1948,
				fotoObra:"https://www.sartle.com/media/artwork/vigil-adolph-gottlieb.jpg",
				textoObra:"Esta pintura é típica das pinturas gráficas de Gottlieb, com a compartimentalização geométrica do espaço plano e o uso de sinais e símbolos aparentemente míticos. Embora os símbolos pareçam arcaicos, Gottlieb inventou a maioria dos seus símbolos, evitando cuidadosamente precedentes e narrativas históricas específicas (embora muitos de seus títulos se refiram à mitologia grega). Assim, Gottlieb pretendia que s suas imagens transcendessem as barreiras da cultura, do tempo e da linguagem. Ele estava interessado na psicologia de Sigmund Freud e Carl Jung, acreditando que os símbolos universais têm o poder de destravar o inconsciente coletivo dos espectadores. Este quadro confronta-nos diretamente com vários rostos semelhantes a máscaras que sugerem fontes não-ocidentais (africanas, por exemplo) contra um fundo escuro que sugere a noite, e talvez a necessidade de estar atento. Os olhos desencarnados podem funcionar como talismãs, ou, no contexto do mito de Édipo sobre o qual Gottlieb pintou uma série, eles também podem referir-se à cegueira. O tema da visão versus cegueira é enfatizado pelo fundo escuro e, simultaneamente, aumenta o significado do título, sugerindo que a vigilância neutraliza a cegueira. As linhas adicionadas e a geometria ajudam a unificar a imagem, mapeando um possível percurso de ação para o espectador."
			},
			{
				nomeObra:"Flotsam at Noon",
				anoObra:1952,
				fotoObra:"https://static.ticimax.cloud/6389/uploads/urunresimleri/buyuk/adolph-gottlieb-flotsam-at-noon-art-pr-80-dc3.jpg",
				textoObra:"Gottlieb começou sua série <i>Imaginary Landscapes</i> em 1952. Aqui, ele explorou simbolicamente a questão da profundidade, criando uma tela dividida por um horizonte oblíquo aparente e sem qualquer ilusão de espaço. Vestígios dos seus pictogramas, incluindo escrita automática e figuras, emergem dos tons terrosos da porção inferior da imagem em contraste com o bloco sólido de cor habitado por formas ovóides e retangulares no topo da composição. A ausência da estrutura de grade dos trabalhos anteriores de Gottlieb atrai novo foco para colorir e formar símbolos. Essa mudança estilística é reforçada pela adição às <i>Imaginary Landscapes</i> de tons e cores mais brilhantes do que as pictografias anteriores. Tanto a expressão quanto o conteúdo estão implícitos na natureza frágil das confusas pictografias embutidas na parte figurativa da imagem, enquanto as formas pairam na parte superior, distantes, mas insistentes."
			},
			{
				nomeObra:"Unstill Life III",
				anoObra:1956,
				fotoObra:"https://www.moma.org/media/W1siZiIsIjIzOTAwNCJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MTQ0MFx1MDAzZSJdXQ.jpg?sha=80c20321c2b2b9c3",
				textoObra:"Trata-se de um terceiro trabalho de uma mesma série. Pode-se ver como a pintura se relaciona com a obra anterior de Gottlieb, com os seus elementos pictográficos e os vestígios de uma grade. Aqui, Gottlieb emprega um grau intransigente de abstração e modernidade com a sua paleta de negros, cinzas e vermelhos. Além disso, o trabalho cada vez mais abstrato e gestual da imagem dentro das enfáticas linhas divisórias agora é lido mais ardentemente na superfície como uma espécie de matriz em oposição a uma grade. O espaço negativo também entra mais em jogo para contrastar e equilibrar as seções internas da composição da pintura. O movimento e a pulsação da pintura contrastam nitidamente com a aparente planicidade do desenho da pintura, refletindo o título da série."
			},
			{
				nomeObra:"Mist",
				anoObra:1961,
				fotoObra:"https://www.guggenheim.org/wp-content/uploads/1961/01/78.2401_ph_web-1.jpg",
				textoObra:"As pinturas de Gottlieb sofreram uma transformação significativa nos anos 50, quando ele abandonou a grade, simplificou as suas formas e aumentou muito a escala das suas telas. Nos <i>Bursts</i> verticais que ele iniciou em 1957, dos quais este trabalho é um exemplo, um disco difuso na zona superior paira sobre uma explosão de pinceladas caligráficas na zona inferior. Apesar da sua abstração, os <i>Bursts</i> evocam uma série de associações, desde paisagens e formas cósmicas até nuvens de cogumelos nucleares. Embora, à primeira vista, essas obras possam parecer totalmente não relacionadas com os pictogramas anteriores, ambas as séries se baseiam na justaposição de formas e são caracterizadas por um dualismo subjacente."
			},
			{
				nomeObra:"Blues",
				anoObra:1962,
				fotoObra:"https://live.staticflickr.com/2688/4406724150_6658810b66_b.jpg",
				textoObra:"A partir de 1956, as monumentais pinturas <i>Burst</i> de Gottlieb desenvolveram-se a partir das <i>Imaginary Landscapes</i>, focando na simplificação do espaço e da cor da série anterior. Embora a paleta mais típica dessas pinturas seja de vermelhos e pretos, este quadro apresenta similarmente uma grande tela verticalmente orientada num campo de cor clara, interrompida apenas por um disco brilhante sobre uma forma solar distorcida de pinceladas grossas e gestuais escuras. A profundidade e o horizonte são completamente eliminados, fazendo com que a cor e a forma sejam o único foco do campo da imagem. As polaridades das cores e formas fornecem a chave para a imagem: abaixo, as linhas grossas que criam uma massa móvel, desordenada, não resolvida; acima, o brilho hipnotizante dos azuis pulsantes e celestes. Em 1962, na data desta pintura, Gottlieb falou sobre a qualidade emocional da cor no seu trabalho. Visualizando a pintura, fica-se impressionado com a gama de efeitos emocionais que o artista explora através da cor azul, progredindo para fora a partir do núcleo, o azul da composição desenvolve-se a partir de um signo subtil e misterioso para uma declaração intensa e vibrante."
			},
			{
				nomeObra:"Burst",
				anoObra:1973,
				fotoObra:"https://media.mutualart.com/Images/2020_06/30/14/145237212/e2fd2404-8b6e-47f5-9b99-04bcf6d945d2_570.Jpeg",
				textoObra:"Pintado apenas um ano antes da morte de Gottlieb, este é um dos últimos quadros da série de pinturas de <i>Burst</i>. A forma alongada da imagem ecoa a composição vertical de suas pinturas anteriores, enfatizando o espaço vazio entre as porções inferior e superior da imagem. Uma zona horizontal bege e comprimida na parte inferior da composição serve de base para as marcas pretas e gestuais mais delicadas e complacentes, empurradas contra a borda inferior. Uma distância dolorosamente longa separa essa área inferior da órbita vermelha pairando no topo da composição, que lança um brilho cada vez mais rosado. Gottlieb achava que o espaço da imagem deveria funcionar como uma questão de escala e tamanho da pintura, como ele disse, <i>o espaço da imagem é o espaço com o qual somos confrontados, em relação ao nosso próprio tamanho</i>."
			},
		]
	},
	//Willem De Kooning
	{
		nomePintor:"Willem De Kooning",
		fotoPintor:"https://images.mubicdn.net/images/cast_member/107033/cache-527744-1585366619/image-w856.jpg",
		textoPintor:[
			"Willem de Kooning nasceu em 24 de abril de 1904, numa família da classe trabalhadora em Roterdão, na Holanda e tornou-se um dos artistas mais influentes da América e do século XX.",
			"Demonstrando desde cedo interesse pela arte, De Kooning foi aprendiz de uma firma líder de design quando tinha doze anos e matriculou-se na escola noturna na prestigiada Academia de Belas Artes e Técnicas de Roterdão que em 1998 foi renomeada em sua homenagem como a Academia Willem de Kooning. Rumou em 1926 para os Estados Unidos com um amigo, estabelecendo-se em Nova Iorque em 1927. Não era a vida de um artista que ele estava procurando nessa altura, pelo contrário, como muitos jovens europeus, era a versão cinematográfica do sonho americano. No entanto, depois de trabalhar brevemente como pintor de casas, estabeleceu-se como artista comercial e mergulhou em sua própria pintura e no mundo artístico de Nova Iorque, fazendo amizade com artistas como Stuart Davis e Arshile Gorky.",
			"Em 1936, durante a Grande Depressão, De Kooning trabalhou na divisão mural da Works Project Administration (WPA), passsando a pintar em tempo integral. No final dos anos 40 e início dos 50, do século passado, De Kooning e os seus contemporâneos de Nova York, incluindo Jackson Pollock, Franz Kline, Robert Motherwell, Adolph Gottlieb, Ad Reinhardt, Barnett Newman e Mark Rothko, tornaram-se notórios por rejeitarem os estilos predominantes, como o Regionalismo, o Surrealismo e o Cubismo, passando a dissolver a relação entre primeiro plano e fundo e usando tinta para criar gestos emotivos e abstratos. Esse movimento foi rotulado como <i>Action Painting</i>, <i>Expressionismo Abstrato</i> ou simplesmente <i>New York School</i>. Até então, Paris era considerada o centro da vanguarda, e a natureza inovadora das contribuições de Picasso era frustrantemente difícil de superar para este grupo de artistas altamente competitivos de Nova Iorque. De Kooning disse claramente: <i>Picasso é o homem a vencer</i>. De Kooning e este grupo finalmente conquistaram os holofotes da Pintura e foram responsáveis pela mudança histórica de atenção para Nova Iorque nos anos seguintes à Segunda Guerra Mundial.",
			"De Kooning tornou-se conhecido como <i>artista entre os artistas</i> entre os seus pares em Nova Iorque e, em 1948, ganhou a aclamação da crítica com sua primeira exposição individual realizada na Charles Egan Gallery. A exposição revelou pinturas a óleo e esmalte densamente trabalhadas, incluindo as suas hoje conhecidas pinturas em preto-e-branco. Esta exposição foi essencial para a reputação de de Kooning. Pouco tempo depois, em 1951, De Kooning fez uma de suas primeiras grandes vendas quando recebeu a Medalha Logan e o Prémio de Compra do Instituto de Arte de Chicago pela sua abstração em grande escala, Escavation (1950). Esta é sem dúvida uma das pinturas mais importantes do século XX. Durante este período, De Kooning ganhou o apoio de Clement Greenberg e, mais tarde, de Harold Rosenberg, os dois críticos principais e rivais de Nova Iorque.",
			"O sucesso de De Kooning não diminuiu a sua necessidade de exploração e experimentação. Em 1953, ele chocou o mundo da arte exibindo uma série de obras figurativas pintadas de forma agressiva, comumente conhecidas como pinturas <i>femininas</i>. Eram mais icónicas do que reais, mas o seu retorno à figuração foi visto por alguns como uma traição aos princípios expressionistas abstratos, que enfatizavam a abstração. Ele perdeu o apoio de Greenberg, mas Rosenberg permaneceu convencido de sua relevância. O Museu de Arte Moderna de Nova Iorque aceitou a mudança de estilo de Kooning como uma evolução e comprou a Woman I (1950 - 1952) em 1953. O que para alguns parecia tão estilisticamente reacionário, para outros era claramente vanguardista. Lutando contra a adesão a qualquer ortodoxia, ele continuou a explorar novos estilos e métodos, muitas vezes desafiando as suas próprias práticas. Costumava dizer, <i>você tem que mudar para permanecer o mesmo</i>.",
			"No final dos anos 50, passou das mulheres para mulheres em paisagens, para o que parecia ser um retorno à abstração <i>pura</i>, com obras respectivamente chamadas de paisagens <i>urbanas</i>, <i>viárias</i> e <i>pastorais</i>; no entanto, ele nunca deixou completamente o mundo dos objetos reais para a pura abstração. Em 1960, ele disse: <i>É realmente absurdo fazer uma imagem, como uma imagem humana, com tinta hoje, quando você pensa sobre isso, já que temos esse problema de fazer ou não fazer isso. Mas, de repente, era ainda mais absurdo não fazê-lo. Então eu temo que eu tenha que seguir os meus desejos</i>. A figura reafirmou-se, agora em sua forma mais carnal.",
			"Grande parte da carreira Kooning é de um constante combate visual entre equilíbrios e desequilíbrios. Na sua última década conseguiu dissipar parte dessa angústia. Saindo de uma metodologia de lixamento, desenho, camadas, raspagem, rotação da tela e repetidamente recuando para considerar cada mudança, as pinturas por vezes serenas dos anos oitenta podem ser vistas como a síntese final de figuração e abstração de De Kooning. Ano após ano, ao longo dos anos 80, de Kooning explorou novas formas de espaço pictórico reveladas por obras com passagens etéreas como fitas; ou alguns com estruturas em que as linhas retas podem flutuar ou parar abruptamente e balancear contra áreas abertas amplas; ou outros de espaços abarrotados, arrojados e líricos. Cores vivas, elementos predominantemente lineares foram justapostos contra áreas brancas subtilmente tonificadas. Com a sua inclinação declarada de abraçar o <i>ordinário</i>, ele estava livre para reconhecer os personagens ou objetos não intelectuais, mundanos ou humorísticos, às vezes perceptíveis nas suas pinturas abstratas. Isso exemplifica novamente a sua insistência na liberdade das ideias doutrinárias sobre o que a arte deveria ser. De Kooning tinha alcançado um lugar mais completamente aberto, menos ansiosamente complexo da sua carreira artística."
		],
		obrasPintor:[
			{
				nomeObra:"Seated Woman",
				anoObra:1940,
				fotoObra:"https://artsdot.com/ADC/Art-ImgScreen-2.nsf/O/A-9H5R4E/$FILE/Willem-de-kooning-seated-woman-1940-private.Jpg",
				textoObra:"Foi a primeira pintura relevante de De Kooning sobre uma mulher, e evoluiu, curiosamente, de uma anterior encomenda para um retrato. O artista parece ter segurado o retrato encomendado e começou a usá-lo para desenvolver novas imagens. Anteriormente usava imagens contemporâneas de mulheres em revistas ou da sua esposa, Elaine, que até se apresentara como modelo quando o tema do retrato não estava disponível. Esses fatores certamente encorajaram De Kooning a ver as possibilidades de usar um retrato para representar a mulher em geral, em vez de um indivíduo específico. Este quadro foi indubitavelmente influenciado por Arshile Gorky, em particular o figurativo <i>O Artista com a sua Mãe</i>."
			},
			{
				nomeObra:"Pink Angels",
				anoObra:1945,
				fotoObra:"https://www.willem-de-kooning.org/images/paintings/pink-angels.jpg",
				textoObra:"Esta obra marcou um estágio importante na evolução de De Kooning da figuração para a abstração na década de 1940. Os biomorfos rosa carnudos do seu trabalho anterior, formas que evocam olhos e outras formas anatómicas, são violentamente rasgados numa pintura que teria sido inspirada pela carnificina da Segunda Guerra Mundial, e os elementos figurativos são dificilmente distinguíveis do fundo amarelo mostarda. Esse enevoamento completo de figura e do fundo foi um passo importante no desenvolvimento de De Kooning para as pinturas em preto e branco da parte posterior da década."
			},
			{
				nomeObra:"Attic",
				anoObra:1949,
				fotoObra:"https://collectionapi.metmuseum.org/api/collection/v1/iiif/482491/1004089/restricted",
				textoObra:"Este quadro é um dos mais conhecidos entre uma série de abstrações em preto e branco realizadas a partir de 1947, por De Kooning. <i>De tudo o que passa por mim, só consigo ver um pouco</i>, disse certa vez o artista, <i>mas estou sempre olhando. E vejo muitas vezes</i>. Ele poderia muito bem ter dito isso deste <i>Attic</i>, pois parece combinar fragmentos de figuras e fundos num turbilhão altamente abstrato e dinâmico. Embora se diga que De Kooning tenha sido motivado a iniciar a série por falta de dinheiro (ele encontrou uma oferta barata de esmalte comercial preto), muitos artistas nesse período estavam experimentando o preto e o branco. Em maior ou menor grau, Motherwell, Kline, Baziotes, Gottlieb e Hofmann, todos trabalharam na paleta restrita, e a <i>Guernica</i> de Picasso, que foi exibido em Nova Iorque em 1939, forneceu-lhes um modelo de peso."
			},
			{
				nomeObra:"Excavation",
				anoObra:1950,
				fotoObra:"https://www.artic.edu/iiif/2/6e72d851-0c15-978f-d0cf-0eadb94c0cf9/full/843,/0/default.jpg",
				textoObra:"Marcou o ponto culminante da fase abstrata de De Kooning dos anos 1940. Como no <i>Attic</i>, ele preocupa-se com a relação entre figura e fundo, e as bordas irregulares das formas biomórficas colidem com força dentro do espaço da composição. No entanto, ao contrário do <i>Attic</i>, ele emprega uma gama de cores primárias para destaques. Este exemplo clássico de pintura de ação estava entre os últimos trabalhos concluídos antes de De Kooning retornar à cor e à figura com enorme entusiasmo na sua série <i>Women</i>."
			},
			{
				nomeObra:"Woman I",
				anoObra:1952,
				fotoObra:"https://www.moma.org/d/assets/W1siZiIsIjIwMTgvMTAvMzEvcjhwY3BxNnFtXzIwMjg2LmpwZyJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ/20286.jpg?sha=dd19ced6e4013605",
				textoObra:"É talvez a pintura mais famosa de De Kooning. O processo da sua criação foi descrito por Thomas B. Hess no seu artigo <i>Willem de Kooning pinta um quadro</i>, e o Museu de Arte Moderna de Nova York comprou-o na sua primeira exposição. De Kooning trabalhou na imagem por dois anos, reformulando-a constantemente e de forma agressiva. O seu agente reparou que a tela frequentemente tinham buracos perfurados pela violência das suas pinceladas."
			},
			{
				nomeObra:"July 4th",
				anoObra:1957,
				fotoObra:"https://scontent.fopo2-2.fna.fbcdn.net/v/t1.6435-9/48390355_1893644870684273_871862469709004800_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=8bfeb9&_nc_ohc=s3wjS25aIvIAX92Adin&_nc_ht=scontent.fopo2-2.fna&oh=00_AfB1T_F5UnxrpFCawB_j2fZDNc_0YBwghMq0gsh9bKZ4BQ&oe=6496B817",
				textoObra:"No final da década de 1950, De Kooning deixou temporariamente de lado a sua preocupação com as mulheres e começou a explorar a paisagem, embora muitas vezes pareça haver poucas referências diretas à paisagem nessas pinturas. Essas obras do final dos anos 1950 e início dos anos 1960 foram feitas durante o período em que De Kooning e Franz Kline compartilhavam uma relação de influência mútua, e a estrutura subjacente ao <i>July 4th</i> é certamente reminiscente de Kline. Curiosamente, Kline, que há muito pintava em preto e branco, começou a usar cores nesse período."
			},
			{
				nomeObra:"Women Singing II",
				anoObra:1967,
				fotoObra:"https://wahooart.com/Art.nsf/O/AQZFFC/$File/Willem-De-Kooning-Women-Singing-II.jpg",
				textoObra:"Este trabalho é típico do estilo de De Kooning ao retornar à figura, ao começar a fazer uma nova série de pinturas de mulheres, pouco depois de se mudar permanentemente para Long Island. Tal como a sua série anterior de mulheres, elas são altamente abstratas, mas são menos ferozes e mais obviamente erotizadas, com lábios vermelhos brilhantes e longos cabelos loiros e mais próximas da caricatura. Foram inspiradas pelas novas modas e ídolos pop da década de 1960."
			},
			{
				nomeObra:"Untitled VII",
				anoObra:1985,
				fotoObra:"https://www.moma.org/d/assets/W1siZiIsIjIwMTgvMTAvMzEvMml4cTdtNGIxXzU0MTE2LmpwZyJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ/54116.jpg?sha=e62e67d7831ffed0",
				textoObra:"Nesta pintura tardia de 1985, De Kooning simplificou enormemente as suas pinceladas e cores. Ao contrário dos seus trabalhos anteriores, que foram caracterizados por superfícies muito ocupadas, neste caso aparentemente emprega um número escasso de pinceladas que são destacadas pela abundância de branco ao redor delas. Ele também se afastou do pesado empastelamento e retornou às superfícies lisas e lixadas de algumas de suas imagens figurativas dos anos 1940. Essas obras foram recebidas como confirmação dos poderes continuados do pintor, no entanto, à medida que a década avançava, ficou claro que as capacidades mentais de Kooning estavam diminuindo, e em 1989 ele foi diagnosticado com a doença de Alzheimer. A década de 1990 assistiu a um debate vigoroso sobre a qualidade do trabalho tardio do pintor, os críticos questionando se ele brotava do seu intelecto ou da sua intuição."
			},
		]
	},
];


